export const AUCTION_ACTIONS_TYPES = {
  FETCH_AUCTIONS_DATA_START: "FETCH_AUCTIONS_DATA_START",
  FETCH_AUCTIONS_DATA_SUCCESS: "FETCH_AUCTIONS_DATA_SUCCESS",
  FETCH_AUCTIONS_DATA_FAILURE: "FETCH_AUCTIONS_DATA_FAILURE",
};
