export const MARKETPLACE_ACTIONS_TYPES = {
    FETCH_MARKETPLACE_START: 'FETCH_MARKETPLACE_START',
    FETCH_MARKETPLACE_SUCCESS: 'FETCH_MARKETPLACE_SUCCESS',
    FETCH_MARKETPLACE_FAILURE: 'FETCH_MARKETPLACE_FAILURE',

}